import { expect, test } from '@playwright/test';
import { adminEmail, adminPassword, apiUrl, createUser, headersFor, login, tokenFor, uniqueName, userPassword } from './helpers.js';

test('requires authentication and rejects impersonation and ordinary-user administration', async ({ request }) => {
  const user = await createUser(request, 'auth-boundary');
  const other = await createUser(request, 'auth-other');
  expect((await request.post(`${apiUrl}/api/session`, { data: { username: user.username } })).status()).toBe(401);
  expect((await request.get(`${apiUrl}/api/conversations?username=${user.username}`)).status()).toBe(401);
  expect((await request.get(`${apiUrl}/api/admin/users`, { headers: headersFor(user.username) })).status()).toBe(403);
  expect((await request.get(`${apiUrl}/api/conversations?username=${other.username}`, { headers: headersFor(user.username) })).status()).toBe(403);
  expect((await request.post(`${apiUrl}/hubs/chat/negotiate?negotiateVersion=1`)).status()).toBe(401);
  expect((await request.get(`${apiUrl}/api/auth/me`, { headers: { Authorization: 'Bearer invalid.external.token' } })).status()).toBe(401);
  expect((await request.post(`${apiUrl}/api/recordings/internal/completed`, { data: { recordingId: user.id } })).status()).toBe(401);
});

test('password login locks out repeated failures and logout revokes existing tokens', async ({ request }) => {
  const user = await createUser(request, 'lockout');
  for (let i = 0; i < 5; i++) {
    const response = await request.post(`${apiUrl}/api/auth/login`, { data: { username: user.username, password: 'Wrong-Password!42' } });
    expect(response.status()).toBe(401);
    expect(await response.json()).toEqual({ error: 'Invalid username or password.' });
  }
  expect((await request.post(`${apiUrl}/api/auth/login`, { data: { username: user.username, password: userPassword } })).status()).toBe(401);
  expect((await request.post(`${apiUrl}/api/auth/logout`, { headers: headersFor(user.username) })).status()).toBe(204);
  expect((await request.get(`${apiUrl}/api/auth/me`, { headers: headersFor(user.username) })).status()).toBe(401);
});

test('admin manages users and roles while protecting own access', async ({ page, request }) => {
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('login.png') });
  await login(page, adminEmail, adminPassword);
  await page.getByRole('button', { name: 'Users', exact: true }).click();
  const email = `${uniqueName('managed')}@e2e.test`;
  await page.getByRole('button', { name: 'Create user', exact: true }).click();
  const editor = page.getByRole('dialog', { name: 'Create user' });
  await editor.getByLabel('Email', { exact: true }).fill(email);
  await editor.getByLabel('First name').fill('Managed');
  await page.screenshot({ path: test.info().outputPath('user-dialog.png') });
  await editor.getByRole('button', { name: 'Save user' }).click();
  await expect(editor).not.toBeVisible();
  await page.locator('.account-workspace').getByLabel('Search users').fill(email);
  const row = page.getByRole('row').filter({ hasText: email });
  await expect(row).toBeVisible({ timeout: 30000 });
  await page.screenshot({ path: test.info().outputPath('users.png') });
  await row.getByRole('button', { name: /Actions for/ }).click();
  await page.screenshot({ path: test.info().outputPath('user-actions.png') });
  await row.getByRole('button', { name: /Actions for/ }).press('Escape');
  await expect(row.getByRole('button', { name: 'View', exact: true })).toBeHidden();
  await row.getByRole('button', { name: /Actions for/ }).click();
  await row.getByRole('button', { name: 'View', exact: true }).click();
  const detailsDialog = page.getByRole('dialog', { name: 'User details' });
  await expect(detailsDialog.getByRole('heading', { name: 'User details' })).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('user-details.png') });
  await detailsDialog.getByRole('button', { name: 'Done', exact: true }).click();
  await row.getByRole('button', { name: /Actions for/ }).click();
  await row.getByRole('button', { name: 'Password authentication', exact: true }).click();
  const passwordDialog = page.getByRole('dialog', { name: 'Password authentication' });
  await page.screenshot({ path: test.info().outputPath('password-dialog.png') });
  await passwordDialog.getByLabel('Allow password authentication').check();
  await passwordDialog.getByLabel('New password').fill(userPassword);
  await passwordDialog.getByRole('button', { name: 'Save password settings' }).click();
  await expect(passwordDialog).not.toBeVisible();
  const token = await tokenFor(request, email);
  await row.getByRole('button', { name: /Actions for/ }).click();
  await row.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Global Admin', { exact: true }).check();
  await page.getByRole('button', { name: 'Save user' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  expect((await request.get(`${apiUrl}/api/admin/users`, { headers: { Authorization: `Bearer ${token}` } })).status()).toBe(200);
  await row.getByRole('button', { name: /Actions for/ }).click();
  await row.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByRole('dialog').getByLabel('Global Admin', { exact: true }).uncheck();
  await page.getByRole('button', { name: 'Save user' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  expect((await request.get(`${apiUrl}/api/admin/users`, { headers: { Authorization: `Bearer ${token}` } })).status()).toBe(403);
  await row.getByRole('button', { name: /Actions for/ }).click();
  await row.getByRole('button', { name: 'Disable', exact: true }).click();
  await page.screenshot({ path: test.info().outputPath('disable-dialog.png') });
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  expect((await request.get(`${apiUrl}/api/auth/me`, { headers: { Authorization: `Bearer ${token}` } })).status()).toBe(401);
  await row.getByRole('button', { name: /Actions for/ }).click();
  await row.getByRole('button', { name: 'Enable', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Confirm' }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  expect((await request.get(`${apiUrl}/api/auth/me`, { headers: { Authorization: `Bearer ${token}` } })).status()).toBe(401);
  const adminToken = await tokenFor(request, adminEmail, adminPassword);
  const profile = await (await request.get(`${apiUrl}/api/auth/me`, { headers: { Authorization: `Bearer ${adminToken}` } })).json();
  expect((await request.patch(`${apiUrl}/api/admin/users/${profile.id}/enabled`, { headers: { Authorization: `Bearer ${adminToken}` }, data: { isEnabled: false } })).status()).toBe(400);
});

test('session persists on reload and password change signs the user out', async ({ page, request }) => {
  const user = await createUser(request, 'profile');
  await login(page, user.username);
  await expect(page.getByRole('button', { name: 'Users', exact: true })).toHaveCount(0);
  await page.reload();
  await expect(page.getByRole('navigation', { name: 'Main sections' })).toBeVisible();
  await page.getByRole('button', { name: 'Edit your profile' }).click();
  await page.getByRole('tab', { name: 'Name', exact: true }).click();
  await page.getByLabel('First name', { exact: true }).fill('Profile');
  await page.getByLabel('Last name', { exact: true }).fill('Updated');
  await page.getByRole('button', { name: 'Save name', exact: true }).click();
  await expect(page.locator('.layout-user strong')).toHaveText('Profile Updated');
  await page.reload();
  await expect(page.locator('.layout-user strong')).toHaveText('Profile Updated');
  await page.getByRole('button', { name: 'Account settings', exact: true }).click();
  await page.screenshot({ path: test.info().outputPath('account.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect.poll(async () => page.locator('.sidebar').evaluate(element => element.getBoundingClientRect().right)).toBeLessThanOrEqual(0);
  await page.evaluate(() => document.documentElement.setAttribute('data-theme', 'dark'));
  await page.screenshot({ path: test.info().outputPath('account-mobile-dark.png'), fullPage: true });
  await page.evaluate(() => document.documentElement.setAttribute('data-theme', 'light'));
  await page.setViewportSize({ width: 1280, height: 720 });
  await page.getByLabel('First name').fill('Updated');
  await page.getByRole('button', { name: 'Save profile' }).click();
  await expect(page.getByRole('status')).toHaveText('Profile saved.');
  await page.getByLabel('Current password').fill(userPassword);
  await page.getByLabel('New password').fill('Updated-User-Password!42');
  await page.getByRole('button', { name: 'Change password', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible();
  await login(page, user.username, 'Updated-User-Password!42');
  await page.getByRole('button', { name: 'Sign out', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Sign out', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible();
});
