import { expect, test } from '@playwright/test';
import { PDFDocument, degrees } from 'pdf-lib';
import { adminEmail, adminPassword, apiUrl, createUser, headersFor, login, openSection, tokenFor, uniqueName } from './helpers.js';

// Full Chromium includes the native PDF viewer; the headless shell only shows its fallback.
test.use({ channel: 'chromium' });

test('sign a PDF, preserve the original, and download signed and audit documents', async ({ page, request }) => {
  const user = await createUser(request, 'pdf-sign');
  const stranger = await createUser(request, 'pdf-stranger');
  const pdf = await PDFDocument.create();
  pdf.addPage([595, 842]).drawText('Document signing acceptance test', { x: 50, y: 780, size: 18 });
  pdf.addPage([595, 842]).setRotation(degrees(90));
  const original = Buffer.from(await pdf.save());
  const name = `${uniqueName('agreement')}.pdf`;
  await login(page, user.username);
  await openSection(page, 'My Documents');
  await page.getByLabel('Choose files to upload').setInputFiles({ name, mimeType: 'application/pdf', buffer: original });
  await page.getByRole('button', { name: `Signatures for ${name}`, exact: true }).click();
  const dialog = page.getByRole('dialog', { name: `Signatures — ${name}`, exact: true });
  await expect(dialog.getByRole('button', { name: 'In-App Signature', exact: true })).toBeVisible();
  const created = page.waitForResponse(response => response.request().method() === 'POST' && /\/signatures$/.test(response.url()));
  await dialog.getByRole('button', { name: 'Open signing editor', exact: true }).click();
  const createdResponse = await created;
  expect(createdResponse.ok(), await createdResponse.text()).toBeTruthy();
  const row = await createdResponse.json();
  const path = `${apiUrl}/api/documents/files/${row.documentId}/signatures/${row.id}`;
  const headers = headersFor(user.username);
  expect((await request.get(`${path}/fields`, { headers: headersFor(stranger.username) })).status()).toBe(404);
  expect((await request.post(`${path}/complete`, { headers: { ...headers, 'Content-Type': 'application/pdf' }, data: original })).status()).toBe(400);
  expect((await request.get(`${path}/original`, { headers })).ok()).toBeTruthy();
  const editor = page.getByRole('dialog', { name: `Sign — ${name}`, exact: true });
  await expect(editor.locator('.react-pdf__Page canvas').first()).toBeVisible();
  await expect(editor.getByText('Drag a field onto the document, or click to add it to page 1.')).toBeVisible();
  await editor.getByRole('button', { name: 'Signature', exact: true }).click();
  await editor.getByRole('button', { name: 'Date', exact: true }).click();
  await editor.getByRole('button', { name: 'Text', exact: true }).click();
  await editor.getByRole('button', { name: 'Save fields', exact: true }).click();
  await expect(editor).toContainText('Fields saved.');
  await editor.getByRole('button', { name: 'Sign', exact: true }).click();
  await editor.getByRole('textbox', { name: 'Text field on page 1', exact: true }).fill('Approved');
  await editor.getByRole('button', { name: 'Signature field on page 1, click to sign', exact: true }).click();
  const canvas = page.getByLabel('Signature drawing area');
  const box = (await canvas.boundingBox())!;
  await page.mouse.move(box.x + 40, box.y + 60);
  await page.mouse.down();
  await page.mouse.move(box.x + 100, box.y + 100, { steps: 10 });
  await page.mouse.move(box.x + 170, box.y + 50, { steps: 10 });
  await page.mouse.up();
  await page.getByRole('dialog').last().getByRole('button', { name: 'Apply', exact: true }).click();
  await page.screenshot({ path: test.info().outputPath('signing-editor.png') });
  const completed = page.waitForResponse(response => response.url() === `${path}/complete`);
  await editor.getByRole('button', { name: 'Finish', exact: true }).click();
  const finished = await completed;
  expect(finished.ok(), await finished.text()).toBeTruthy();
  expect((await finished.json()).status).toBe('completed');
  const preview = page.getByRole('dialog', { name: `Preview signed-${name}`, exact: true });
  await expect(preview.locator('.react-pdf__Page canvas').first()).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('signed-pdf.png') });
  const restoredSize = (await preview.boundingBox())!;
  await preview.getByRole('button', { name: 'Browser', exact: true }).click();
  const browserPdf = preview.locator('object[type="application/pdf"]');
  await expect(browserPdf).toBeVisible();
  expect((await browserPdf.boundingBox())!.height).toBeGreaterThan(restoredSize.height - 130);
  await preview.getByRole('button', { name: 'Full screen', exact: true }).click();
  await expect.poll(async () => Math.round((await preview.boundingBox())!.width)).toBe(page.viewportSize()!.width);
  await expect.poll(async () => Math.round((await preview.boundingBox())!.height)).toBe(page.viewportSize()!.height);
  await page.screenshot({ path: test.info().outputPath('browser-pdf-maximized.png') });
  await preview.getByRole('button', { name: 'Restore size', exact: true }).click();
  await expect.poll(async () => Math.round((await preview.boundingBox())!.width)).toBe(Math.round(restoredSize.width));
  await preview.getByRole('button', { name: 'In-app', exact: true }).click();
  await expect(preview.locator('.react-pdf__Page canvas').first()).toBeVisible();
  const signed = await request.get(`${path}/download`, { headers });
  expect(signed.ok()).toBeTruthy();
  expect((await PDFDocument.load(await signed.body())).getPageCount()).toBe(2);
  expect(await signed.body()).not.toEqual(original);
  const source = await request.get(`${apiUrl}/api/documents/files/${row.documentId}/content?username=${encodeURIComponent(user.username)}`, { headers });
  expect(await source.body()).toEqual(original);
  const audit = await request.get(`${path}/download?audit=true`, { headers });
  expect(audit.ok()).toBeTruthy();
  expect((await PDFDocument.load(await audit.body())).getPageCount()).toBeGreaterThan(0);
  expect((await request.put(`${path}/fields`, { headers, data: { fields: [] } })).status()).toBe(409);
  expect((await request.delete(path, { headers })).status()).toBe(409);
  await page.reload();
  await openSection(page, 'My Documents');
  await page.getByRole('button', { name: `Signatures for ${name}`, exact: true }).click();
  await dialog.getByRole('tab', { name: 'Signing requests', exact: true }).click();
  await expect(dialog).toContainText('completed');
  await dialog.getByRole('button', { name: 'Preview audit record', exact: true }).click();
  const auditPreview = page.getByRole('dialog', { name: `Preview audit-${name}`, exact: true });
  await expect(auditPreview.locator('.react-pdf__Page canvas').first()).toBeVisible();
  await page.screenshot({ path: test.info().outputPath('audit-record.png') });
});

test('signing draft validates requests, is idempotent, and can be discarded', async ({ page, request }) => {
  const user = await createUser(request, 'sign-draft');
  await login(page, user.username);
  await openSection(page, 'My Documents');
  const pdf = await PDFDocument.create();
  pdf.addPage();
  const name = `${uniqueName('draft')}.pdf`;
  const original = Buffer.from(await pdf.save());
  await page.getByLabel('Choose files to upload').setInputFiles({ name, mimeType: 'application/pdf', buffer: original });
  await page.getByRole('button', { name: `Signatures for ${name}`, exact: true }).click();
  const headers = headersFor(user.username);
  const listing = await request.get(`${apiUrl}/api/documents?username=${encodeURIComponent(user.username)}`, { headers });
  const file = (await listing.json()).files.find((item: { name: string }) => item.name === name);
  const path = `${apiUrl}/api/documents/files/${file.id}/signatures`;
  const userQuery = `username=${encodeURIComponent(user.username)}`;
  const usage = async () => (await (await request.get(`${apiUrl}/api/documents/storage?${userQuery}`, { headers })).json()).usedBytes as number;
  const before = await usage();
  const input = { provider: 'InApp', subject: 'Draft', recipients: [], clientRequestId: crypto.randomUUID() };
  const create = await request.post(path, { headers, data: input });
  expect(create.ok(), await create.text()).toBeTruthy();
  const row = await create.json();
  expect(await usage()).toBe(before + original.length);
  expect((await (await request.post(path, { headers, data: input })).json()).id).toBe(row.id);
  expect((await request.post(path, { headers, data: { ...input, clientRequestId: crypto.randomUUID(), provider: 'DocuSign', recipients: [{ name: 'Signer', email: 'signer@example.com' }] } })).status()).toBe(409);
  expect((await request.put(`${path}/${row.id}/fields`, { headers, data: { fields: [{ id: 'invalid', type: 'signature', page: 1, x: 2, y: 0, width: 1, height: 1, value: null }] } })).status()).toBe(400);
  pdf.getPage(0).drawText('Replacement content', { x: 50, y: 700 });
  const replacement = Buffer.from(await pdf.save());
  const replaced = await request.put(`${apiUrl}/api/documents/files/${file.id}/content?${userQuery}`, {
    headers, multipart: { file: { name, mimeType: 'application/pdf', buffer: replacement } },
  });
  expect(replaced.ok(), await replaced.text()).toBeTruthy();
  expect(await (await request.get(`${path}/${row.id}/original`, { headers })).body()).toEqual(original);
  const beforeDiscard = await usage();
  expect((await request.delete(`${path}/${row.id}`, { headers })).ok()).toBeTruthy();
  expect((await request.get(`${path}/${row.id}/fields`, { headers })).status()).toBe(404);
  expect(await usage()).toBe(beforeDiscard - original.length);
  const adminToken = await tokenFor(request, adminEmail, adminPassword);
  const limit = await request.put(`${apiUrl}/api/documents/storage-management/${user.id}/limit?username=${encodeURIComponent(adminEmail)}`, {
    headers: { Authorization: `Bearer ${adminToken}` }, data: { limitBytes: await usage() },
  });
  expect(limit.ok(), await limit.text()).toBeTruthy();
  const noSpace = await request.post(path, { headers, data: { ...input, clientRequestId: crypto.randomUUID() } });
  expect(noSpace.status()).toBe(409);
  expect(await noSpace.text()).toContain('storage');
});
