import { expect, test } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { apiUrl, createUser, headersFor, login } from './helpers.js';
import { createNode, csvCell, definitionIssues, flatten, moveNode, visibleAnswers, type FormDefinition, type FormDetail, type ResponsePage } from '../../frontend/src/components/forms/formModel.js';

test('form model preserves nested moves, prevents cycles, and excludes hidden answers', () => {
  const choice = { ...createNode('yesno'), id: 'choice' };
  const hidden = { ...createNode('text'), id: 'hidden', conditions: [{ questionId: 'choice', operator: 'equals', value: 'Yes' }] };
  const columns = createNode('columns');
  columns.children[0].children.push(hidden);
  const nodes = [choice, columns];
  expect(visibleAnswers(nodes, { choice: ['No'], hidden: ['stale'] }).answers).toEqual({ choice: ['No'] });
  expect(visibleAnswers(nodes, { choice: ['Yes'], hidden: ['kept'] }).answers.hidden).toEqual(['kept']);
  expect(moveNode(nodes, columns.id, columns.children[0].id, 0)).toBe(nodes);
  const moved = moveNode(nodes, hidden.id, columns.children[1].id, 0);
  expect(moved[1].children[0].children).toHaveLength(0);
  expect(moved[1].children[1].children[0].id).toBe('hidden');
  expect(csvCell('=HYPERLINK("bad")')).toBe('"\'=HYPERLINK(""bad"")"');
  expect(definitionIssues({ title: 'Test', description: '', confirmationMessage: '', nodes: [hidden, choice] })).toHaveLength(1);
});

test('Forms API enforces ownership, publication snapshots, validation, retries, and deletion', async ({ request }) => {
  const owner = await createUser(request, 'formowner');
  const stranger = await createUser(request, 'formother');
  const headers = headersFor(owner.username);
  const otherHeaders = headersFor(stranger.username);
  expect((await request.get(`${apiUrl}/api/forms/`)).status()).toBe(401);
  const created = await request.post(`${apiUrl}/api/forms/`, { headers });
  expect(created.ok(), await created.text()).toBeTruthy();
  let form = await created.json() as FormDetail;
  const base = `${apiUrl}/api/forms/${form.id}`;
  const publicBase = `${apiUrl}/api/public/forms/${form.shareToken}`;
  expect((await request.get(publicBase)).status()).toBe(404);
  expect((await request.get(base, { headers: otherHeaders })).status()).toBe(404);
  const qrUrl = `${base}/qr-code?baseUrl=${encodeURIComponent('https://example.test/chat/')}`;
  expect((await request.get(qrUrl)).status()).toBe(401);
  expect((await request.get(qrUrl, { headers: otherHeaders })).status()).toBe(404);
  expect((await request.get(`${base}/qr-code?baseUrl=javascript:alert(1)`, { headers })).status()).toBe(400);
  const qr = await request.get(qrUrl, { headers });
  expect(qr.ok(), await qr.text()).toBeTruthy();
  expect(qr.headers()['content-type']).toBe('image/png');
  expect(qr.headers()['cache-control']).toBe('no-store');
  expect((await qr.body()).subarray(0, 8).toString('hex')).toBe('89504e470d0a1a0a');
  expect((await request.get(`${base}/responses`, { headers: otherHeaders })).status()).toBe(404);
  expect((await request.post(`${base}/duplicate`, { headers: otherHeaders })).status()).toBe(404);
  expect((await request.delete(`${base}?revision=1`, { headers: otherHeaders })).status()).toBe(404);
  const choice = { ...createNode('yesno'), id: 'choice', label: 'More details?', required: true };
  const email = { ...createNode('email'), id: 'email', required: true, conditions: [{ questionId: choice.id, operator: 'equals', value: 'Yes' }] };
  const columns = createNode('columns');
  columns.children[0].children = [email];
  columns.children[1].children = [createNode('columns')];
  const definition: FormDefinition = { title: 'Version one', description: 'Nested survey', confirmationMessage: 'Thanks!', nodes: [choice, columns] };
  const invalid = { ...definition, nodes: [email, choice] };
  expect((await request.put(base, { headers, data: { revision: form.revision, definition: invalid } })).status()).toBe(400);
  expect((await request.put(base, { headers: otherHeaders, data: { revision: form.revision, definition } })).status()).toBe(404);
  const saved = await request.put(base, { headers, data: { revision: form.revision, definition } });
  expect(saved.ok(), await saved.text()).toBeTruthy();
  form = await saved.json();
  expect((await request.put(base, { headers, data: { revision: 1, definition } })).status()).toBe(409);
  expect((await request.post(`${base}/publish`, { headers: otherHeaders, data: { revision: form.revision } })).status()).toBe(404);
  const published = await request.post(`${base}/publish`, { headers, data: { revision: form.revision } });
  expect(published.ok(), await published.text()).toBeTruthy();
  form = await published.json();
  const publicForm = await (await request.get(publicBase)).json();
  expect(publicForm.definition.title).toBe('Version one');
  expect(publicForm).not.toHaveProperty('ownerId');
  expect((await request.post(`${publicBase}/responses`, { data: { version: 1, submissionKey: randomUUID(), answers: {} } })).status()).toBe(400);
  expect((await request.post(`${publicBase}/responses`, { data: { version: 1, submissionKey: randomUUID(), answers: { choice: ['Yes'] } } })).status()).toBe(400);
  const submission = { version: 1, submissionKey: randomUUID(), answers: { choice: ['No'], email: ['hidden@example.com'], unknown: ['forged'] } };
  const attempts = await Promise.all([request.post(`${publicBase}/responses`, { data: submission }), request.post(`${publicBase}/responses`, { data: submission })]);
  for (const response of attempts) {
    expect(response.ok(), await response.text()).toBeTruthy();
  }
  let responses = await (await request.get(`${base}/responses`, { headers })).json() as ResponsePage;
  expect(responses.total).toBe(1);
  expect(responses.items[0].answers).toEqual({ choice: ['No'] });
  const savedAgain = await request.put(base, { headers, data: { revision: form.revision, definition: { ...definition, title: 'Version two' } } });
  form = await savedAgain.json();
  expect((await (await request.get(publicBase)).json()).definition.title).toBe('Version one');
  const secondPublication = await request.post(`${base}/publish`, { headers, data: { revision: form.revision } });
  form = await secondPublication.json();
  expect(form.publishedVersion).toBe(2);
  expect((await request.post(`${publicBase}/responses`, { data: { ...submission, submissionKey: randomUUID() } })).status()).toBe(409);
  responses = await (await request.get(`${base}/responses`, { headers })).json();
  expect(responses.items[0].definition.title).toBe('Version one');
  const duplicate = await request.post(`${base}/duplicate`, { headers });
  const copy = await duplicate.json() as FormDetail;
  expect(copy.isPublished).toBe(false);
  expect(copy.shareToken).not.toBe(form.shareToken);
  expect((await (await request.get(`${apiUrl}/api/forms/${copy.id}/responses`, { headers })).json()).total).toBe(0);
  const closed = await request.post(`${base}/close`, { headers, data: { revision: form.revision } });
  form = await closed.json();
  expect((await request.get(publicBase)).status()).toBe(404);
  expect((await request.post(`${publicBase}/responses`, { data: { ...submission, version: 2, submissionKey: randomUUID() } })).status()).toBe(400);
  const deleted = await request.delete(`${base}?revision=${form.revision}`, { headers });
  expect(deleted.status(), await deleted.text()).toBe(204);
  expect((await request.get(`${base}/responses`, { headers })).status()).toBe(404);
  expect((await request.delete(`${apiUrl}/api/forms/${copy.id}?revision=${copy.revision}`, { headers })).status()).toBe(204);
});

test('build nested conditional form by drag and drop, publish, submit anonymously, and export', async ({ page, browser, request }, testInfo) => {
  const user = await createUser(request, 'formui');
  await login(page, user.username);
  await page.getByRole('navigation', { name: 'Main sections' }).getByRole('button', { name: 'Forms', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your forms' })).toBeVisible();
  await page.getByRole('button', { name: 'New form', exact: true }).click();
  await page.getByLabel('Title', { exact: true }).fill('Customer research');
  await page.locator('.forms-palette').getByRole('button', { name: 'Short answer', exact: true }).dragTo(page.locator('.forms-canvas > .forms-block-list > .forms-drop'));
  await page.getByLabel('Question', { exact: true }).fill('Name');
  await page.getByLabel('Required answer').check();
  await page.locator('.forms-palette').getByRole('button', { name: 'Columns', exact: true }).click();
  await page.locator('.forms-column-title').filter({ hasText: 'Column 1' }).click();
  await page.locator('.forms-palette').getByRole('button', { name: 'Columns', exact: true }).click();
  await expect(page.locator('.forms-columns-builder')).toHaveCount(2);
  await page.locator('.forms-column-title').filter({ hasText: 'Column 1' }).last().click();
  await page.locator('.forms-palette').getByRole('button', { name: 'Email', exact: true }).click();
  await page.getByLabel('Question', { exact: true }).fill('Contact email');
  await page.getByLabel('Required answer').check();
  await page.getByRole('button', { name: 'Add condition' }).click();
  await page.locator('.forms-condition').getByLabel('Condition question', { exact: true }).selectOption({ label: 'Name' });
  await page.getByLabel('Value (case sensitive)').fill('Show');
  await page.locator('.forms-palette').getByRole('button', { name: 'Time', exact: true }).click();
  await page.getByLabel('Question', { exact: true }).fill('Appointment time');
  await page.getByLabel('Required answer').check();
  await page.locator('.forms-palette').getByRole('button', { name: 'Date & time', exact: true }).click();
  await page.getByLabel('Question', { exact: true }).fill('Appointment date and time');
  await page.getByLabel('Required answer').check();
  await page.screenshot({ path: testInfo.outputPath('forms-builder.png'), fullPage: true });
  const canvas = page.getByRole('region', { name: 'Form canvas', exact: true });
  const paletteBefore = await page.locator('.forms-palette').boundingBox();
  const inspectorBefore = await page.locator('.forms-inspector').boundingBox();
  const headerBefore = await page.locator('.forms-header').boundingBox();
  await canvas.evaluate(element => { element.scrollTop = element.scrollHeight; });
  expect(await canvas.evaluate(element => element.scrollTop)).toBeGreaterThan(0);
  expect(await page.locator('.forms-palette').boundingBox()).toEqual(paletteBefore);
  expect(await page.locator('.forms-inspector').boundingBox()).toEqual(inspectorBefore);
  expect(await page.locator('.forms-header').boundingBox()).toEqual(headerBefore);
  expect(await page.locator('.forms-view').evaluate(element => element.scrollTop)).toBe(0);
  await canvas.evaluate(element => { element.scrollTop = 0; });
  await page.getByRole('button', { name: 'Publish form', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Share your form' })).toBeVisible();
  const url = await page.getByLabel('Response link').inputValue();
  const qrImage = page.getByRole('img', { name: 'QR code for Customer research' });
  await expect(qrImage).toBeVisible();
  await expect.poll(() => qrImage.evaluate(image => (image as HTMLImageElement).naturalWidth)).toBeGreaterThan(0);
  const qrDownloadEvent = page.waitForEvent('download');
  await page.getByRole('link', { name: 'Download QR code' }).click();
  expect((await qrDownloadEvent).suggestedFilename()).toMatch(/^form-.*-qr\.png$/);
  const anonymous = await browser.newPage();
  try {
    await anonymous.goto(url);
    await expect(anonymous.getByRole('heading', { name: 'Customer research' })).toBeVisible();
    await expect(anonymous.getByRole('heading', { name: /^Column [1-4]$/ })).toHaveCount(0);
    await expect(anonymous.getByRole('textbox', { name: 'Contact email' })).toHaveCount(0);
    await anonymous.getByRole('textbox', { name: 'Name', exact: true }).fill('Show');
    await anonymous.getByRole('textbox', { name: 'Contact email' }).fill('respondent@example.com');
    await anonymous.locator('input[type="time"]').fill('09:30');
    await anonymous.locator('input[type="datetime-local"]').fill('2026-10-08T14:45');
    await anonymous.setViewportSize({ width: 390, height: 844 });
    expect(await anonymous.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await anonymous.screenshot({ path: testInfo.outputPath('forms-public-mobile.png'), fullPage: true });
    await anonymous.getByRole('button', { name: 'Submit response' }).click();
    await expect(anonymous.getByRole('heading', { name: 'Response submitted' })).toBeVisible();
  } finally {
    await anonymous.close();
  }
  await page.getByRole('button', { name: 'Responses', exact: true }).click();
  await expect(page.getByRole('heading', { name: '1 responses' })).toBeVisible();
  await page.locator('.forms-response summary').click();
  await expect(page.locator('.forms-response')).toContainText('respondent@example.com');
  await expect(page.locator('.forms-response')).toContainText('09:30');
  await expect(page.locator('.forms-response')).toContainText('2026-10-08T14:45');
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export CSV' }).click();
  const download = await downloadEvent;
  expect(download.suggestedFilename()).toBe('Customer_research-responses.csv');
  const downloadPath = testInfo.outputPath('responses.csv');
  await download.saveAs(downloadPath);
  await page.getByRole('button', { name: 'Build', exact: true }).click();
  await page.getByLabel('Title', { exact: true }).fill('Draft edit');
  await page.getByRole('button', { name: 'Undo', exact: true }).click();
  await expect(page.getByLabel('Title', { exact: true })).toHaveValue('Customer research');
  const list = await (await request.get(`${apiUrl}/api/forms/`, { headers: headersFor(user.username) })).json() as FormDetail[];
  const form = list.find(item => item.title === 'Customer research')!;
  const detail = await (await request.get(`${apiUrl}/api/forms/${form.id}`, { headers: headersFor(user.username) })).json() as FormDetail;
  expect(flatten(detail.definition.nodes).filter(node => node.kind === 'columns')).toHaveLength(2);
  await request.delete(`${apiUrl}/api/forms/${form.id}?revision=${form.revision}`, { headers: headersFor(user.username) });
});
