<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Communication.CallAutomation" Version="1.6.0" />
    <PackageReference Include="Azure.Communication.Identity" Version="1.3.1" />
    <PackageReference Include="Azure.Identity" Version="1.21.0" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.1" />
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.2" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <ProjectReference Include="../ChatApp.Application/ChatApp.Application.csproj" />
    <ProjectReference Include="../ChatApp.Persistence/ChatApp.Persistence.csproj" />
  </ItemGroup>
</Project>
